-- 1. 영어영문학과(학과코드 002) 학생의 학번,이름,입학년도를 입학년도 빠른 순으로 정렬하는 sql
SELECT 
    STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO != 002
ORDER BY ENTRANCE_DATE;


-- 2. 교수 중 이름이 세글자가 아닌 교수가 한 명 있는데, 그 교수의 이름과 주민번호를 화면에 출력하는 SQL
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;



-- 3. 남자 교수들의 이름과 나이를 출력하는 SQL문 (단, 나이를 오름차순 정렬)
SELECT PROFESSOR_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, '19'||SUBSTR(PROFESSOR_SSN,0,6))/12)
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY SUBSTR(PROFESSOR_SSN,0,6) DESC;



-- 4. 교수들의 이름 중 성을 제외한 이름만 출력하는 SQL문장을 작성하쇼 (단, 성이 2글자 이상인 교수는 없!)
SELECT 
    SUBSTR(PROFESSOR_NAME, 2)
FROM TB_PROFESSOR;

SELECT STUDENT_NAME,STUDENT_SSN, ENTRANCE_DATE,
--SELECT
--MONTHS_BETWEEN('2012/03/01', '1993/08/26')/12.0
CEIL(MONTHS_BETWEEN(ENTRANCE_DATE , TO_DATE(SUBSTR(STUDENT_SSN,1,6)))/12.0)+1 "입학시나이"
--FROM DUAL;
FROM TB_STUDENT;

-- 5. 재주생 입학자 구하려고 하는데, 어떻게 찾으실? 19살에 입학하면 재수 하지 않은것으로 간주함
-- 주민앞자리 + 19 하면  원래 재수 안한 학번임**
SELECT STUDENT_NAME,STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE
CEIL(MONTHS_BETWEEN(ENTRANCE_DATE , TO_DATE(SUBSTR(STUDENT_SSN,1,6)))/12.0)+1 > 20








