-- 01 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서명, 직급, 입사일, 순위 조회
-- ??? 뭔가 답이 좀 다른데..?? !!??
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, RANK,TOTAL_SAL
FROM
(
    SELECT
    EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE,(SALARY + NVL(BONUS,0))*12 TOTAL_SAL,
    RANK() OVER(ORDER BY (SALARY + NVL(BONUS,0)) *12 DESC) RANK    
    FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE
    JOIN JOB USING(JOB_CODE)
)
WHERE RANK <= 5;

    SELECT
    EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE,(SALARY + NVL(BONUS,0))*12 TOTAL_SAL,
    RANK() OVER(ORDER BY (SALARY + NVL(BONUS,0)) *12 DESC) RANK    
    FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE
    JOIN JOB USING(JOB_CODE);


-- 02 부서별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서명, 부서별 급여 합계 조회
-- (방법은 여러 가지..! 가급적으로 서브쿼리 사용해보세요!)

SELECT DEPT_TITLE ,DEPT_SALARY
FROM 
(
    SELECT SUM(SALARY) DEPT_SALARY ,DEPT_TITLE
    FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE
    GROUP BY DEPT_TITLE
)
WHERE DEPT_SALARY > (SELECT SUM(SALARY) FROM EMPLOYEE) * 0.2;
SELECT SUM(SALARY)* 0.2 FROM EMPLOYEE ;

-- 03 WITH을 이용하여 급여 합과 급여 평균 조회
WITH TESTAA AS 
(
SELECT SUM(SALARY) SUM_SAL, AVG(SALARY) AVG_SAL
FROM EMPLOYEE
)
SELECT SUM_SAL, AVG_SAL
FROM TESTAA;

