DROP TABLE MEMBER;


CREATE TABLE MEMBER(
ID VARCHAR2(100),
PASSWORD VARCHAR2(150) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
ADDRESS VARCHAR2(300),
CONSTRAINT PK_NAME PRIMARY KEY(NAME)
);


UPDATE MEMBER SET NAME='testname', ADDRESS='testAddr' WHERE ID='test';


Select * from member;

DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
MEMBERID VARCHAR2(100),
MEMBERPASS VARCHAR2(150) NOT NULL,
MEMBERNAME VARCHAR2(50) NOT NULL,
MEMBERADDR VARCHAR2(300),
CONSTRAINT PK_ID PRIMARY KEY(MEMBERID)
);

INSERT INTO MEMBER2(MEMBERID, MEMBERPASS, MEMBERNAME, MEMBERADDR)
SELECT ID, PASSWORD, NAME , ADDRESS FROM MEMBER;
COMMIT;


SELECT * FROM MEMBER2 Where MEMBERID LIKE '%test%';
